matrix:
  include:
    - language: python
      python:
        - 3.8
      services:
        - postgresql
      before_install:
        - psql -c 'create database test_db;' -U postgres
      install:
        - pip install -r requirements-dev.txt
      env:
        - DJANGO_CONFIGURATION=TravisCI
      script:
        - pytest

    - language: node_js
      install:
        - yarn install
      script:
        - yarn build

notifications:
  email: false
