name: Tests

# Test phe nsc-recommendationsp

on:
  push:
  pull_request:

jobs:
  test-backend:
    name: phe nsc-recommendationsp backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
      redis:
        image: postgres
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          pytest
        env:
          DJANGO_CONFIGURATION: Dev
          DATABASE_ENGINE: postgresql
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          REDIS_SERVICE_HOST: localhost
